services:
  - type: web
    name: chemical-backend
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn equipment_visualizer.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: chemical-db
          property: connectionString

databases:
  - name: chemical-db
    databaseName: chemical_equipment
    user: chemical_user
    region: oregon
    plan: free
