services:
  - type: web
    name: chemical-backend
    env: python
    region: singapore
    plan: free
    branch: main
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn equipment_visualizer.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chemical-db
          property: connectionString
    autoDeploy: true

databases:
  - name: chemical-db
    databaseName: chemical_equipment
    user: chemical_user
    plan: free
